assets/src/ba_data/python/bastd/actor/spaz.py

Timer does not work, explodes only when touched.

Fix Spaz.curse() method

---

assets/src/ba_data/python/bastd/ui/store/browser.py

Confirm window did't appear.
Now it should work but.. I think ba.internal.serverget (i.e. ServerCallThread) doesn't work, it doesn't run callback.

Fix buy method in StoreBrowserWindow

---

assets/src/ba_data/python/bastd/ui/mainmenu.py

Functionality for adding custom menu entities didn't work correctly (in co-op sessions was no retry button).
I really don't know what this line do here:neutral_face:

Fix pause menu

---

assets/src/ba_data/python/ba/_gameresults.py
assets/src/ba_data/python/bastd/activity/coopscorescreen.py
assets/src/ba_data/python/bastd/activity/multiteamendscreen.py
assets/src/ba_data/python/bastd/game/elimination.py
assets/src/ba_data/python/bastd/game/race.py
assets/src/ba_data/python/bastd/ui/gather.py
assets/src/ba_data/python/efro/util.py

If some scores are equal, I get TypeError while Python compares dict objects.
I think that it’s also necessary to sort by time, but it will take a lot of effort and I don’t know if it is necessary.

Fix score sorting in co-op scorescreen activity

---

assets/src/ba_data/python/ba/_lobby.py

If chooser changes character too quickly, server just breaks down with some error (but it not restarts, just does not let anyone in).
This protection kicks players what changes characters too quickly and too much.

Character-Character-Attack protection

---

CHANGELOG.md
CONTRIBUTORS.md
tools/batools/pcommand.py

If you run `./bombsquad_server` (instead of `python3.7 <file>`), it returns the below error because of using `-O` flag for `python3.7` in the shebang line:
```
$ ./bombsquad_server
/usr/bin/env: ‘python3.7 -O’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```
This PR adds `-S` flag to `/usr/bin/env` to resolve this issue.
> **-S, --split-string=S**
>               process and split S into separate arguments; used to pass
>               multiple arguments on shebang lines
> https://man7.org/linux/man-pages/man1/env.1.html
|   | Type |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |
None

Use -S flag for /usr/bin/env

---

.idea/dictionaries/roman.xml
assets/.asset_manifest_public.json
assets/Makefile
assets/src/ba_data/python/ba/__init__.py
assets/src/ba_data/python/ba/_keyboard.py
assets/src/ba_data/python/ba/_meta.py
assets/src/ba_data/python/bastd/ui/onscreenkeyboard.py
assets/src/ba_data/python/keyboards.py

A new feature that provides a meta tag for custom keyboards offered in #137.
- To change keymap/keyboard quick press space two times.
- Keyboard may have unlimited pages with some extra chars or letters.
A word about standard emojis (#123)... Currently only Android (and Apple) devices can render them (this mentioned in #45) so is using them in all platfoms correct? For example, I see following:

New meta-tag '# ba_meta export keyboard'

---

CHANGELOG.md
assets/src/ba_data/python/ba/_meta.py

Meta subsytem now enables new plugin by default in headless builds to allow server admins to get their modified server working 'out-of-the-box', without manually updating the config.
| ✓  | :sparkles: New feature |

Meta subsytem now enables new plugin by default in headless builds

---

src/ballistica/scene/node/spaz_node.cc

It's not required to set `jump_pressed_` again as it is already set beforehand in the 4th line:
https://github.com/efroemling/ballistica/blob/3d52e05bfbb6fd57645cd4dbeea6b9837daa7247/src/ballistica/scene/node/spaz_node.cc#L1089-L1117
|   | Type |
| ✓  | :hammer: Refactoring  |

Remove redundant code

---

.idea/dictionaries/ericf.xml
CHANGELOG.md
CONTRIBUTORS.md
assets/src/ba_data/python/bastd/ui/gather/manualtab.py
ballisticacore-cmake/.idea/dictionaries/ericf.xml

Manual Tab now have  2 sub_tab 
1) Join a party by address 
2) Join a saved party
sub_tab 1. _Join a party by address_ - now have one extra button SAVE to save address and port  of party
sub_tab 2. _Join a saved party_ - has list of all saved parties with 3 buttons (connect,rename,delete).
|   | Type |
| ✓  | :sparkles: New feature |

added feature to save party in manual tab

---

CHANGELOG.md
CONTRIBUTORS.md
assets/src/ba_data/python/bastd/game/elimination.py

Some players immediately leave the game mid-way in elimination maps
when they have the final turn in the team and they are about to
die/fall off a cliff, which causes the game to draw when the opponent
team should have been declared the winner.
The game will now check if the player to leave the elimination game was
the last player in the team and in case they were so, mark their team
score so the opponent team is declared as the winner.
|   | Type |
| ✓  | :bug: Bug fix  |

 Set winner when player leaves elimination mid-game

---

tools/batools/build.py

If some python package on the system has been installed in editable mode through
```bash
$ python setup.py build
or
$ pip install -e .
```
then
```
$ pip list
```
returns three values for that specific package, in this order: `<package-name> <package-version> <package-install-directory>`. The build script currently fails to parse such packages correctly since it expects only two values (the initial two - `<package-name> <package-version>`):
```bash
$ make cmake-server
Checking environment...                              
Traceback (most recent call last):
File "tools/pcommand", line 52, in <module>
pcommand_main(globals())
File "/home/ritiek/Downloads/ballistica/tools/efrotools/pcommand.py", line 56, in pcommand_main
funcs[sys.argv[1]]()                             
File …
```

Build: parse pip output correctly

---

assets/src/ba_data/python/bastd/gameutils.py

After changing the storage location of the `SharedObjects` instance (bc22359dcd06b1dea6a1c767ba350783f4fb53f5), you forgot to change the check in `SharedObjects.__init__`

Fix SharedObjects

---

CONTRIBUTORS.md
assets/src/ba_data/python/ba/_gameactivity.py
assets/src/ba_data/python/ba/_player.py

Allows you to add your own PlayerSpaz types
Example:
```python
import ba
from bastd.actor.playerspaz import PlayerSpaz
class MyPlayerSpaz(PlayerSpaz):
def on_jump_press(self) -> None:
ba.screenmessage("Hello from my playerspaz!")
class Player(ba.Player['Team']):
playerspaztype = MyPlayerSpaz
class Team(ba.Team[Player]):
pass
class MyGame(ba.TeamGameActivity[Player, Team]):
name = "Example"
```

Own PlayerSpaz

---

CHANGELOG.md
src/ballistica/graphics/camera.cc

Line 725 looks like something that tries to slowly return `shake_pos_` to {0, 0, 0}, but it can't be successful if we reset `shake_vel_` (line 730).
https://github.com/efroemling/ballistica/blob/3197caaff42338529d74645648808832f82762c3/src/ballistica/graphics/camera.cc#L723-L731
Closes #511

Fix 'Disable Camera Shake' option

---

assets/src/ba_data/python/ba/_playlist.py

Filter out unavailable maps from a playlist to avoid blank screen/crashes.
Right now if playlist contains a map which is not installed on server then server stucks on scorescreen.

filtering unavailable maps from playlist

---

CONTRIBUTORS.md
src/assets/ba_data/python/bascenev1lib/actor/playerspaz.py

PlayerSpaz should use the scene's time for handling things, but it accidentally got changed to use the app time instead during the transition to api 8

Fixed PlayerSpaz using bs.apptime() instead of bs.time() for last_attacked_time

---

src/assets/ba_data/python/bascenev1lib/game/hockey.py

There was always a bug annoying me when working with mods regarding how the hockey puck handles a non-immediate bs.DieMessage, causing the puck to respawn indefinitely, this PR ensures that this won't happen.

Fixed issue with hockey puck dying

---

CONTRIBUTORS.md
src/assets/ba_data/python/bascenev1/_session.py

Imagine killing someone, them having to wait 7 seconds to respawn, and they just disconnect and reconnect and they're able to hop in the game immediately without having to wait even a second.
Originally a plugin by @rikkolovescats, this PR disallows any pb-id from joining the session for 10 seconds once the player leaves the session, this system works like the system in the c-layer that disallows people from joining for 10 seconds after they leave, but this system supports disconnections and reconnections, allowing a fair game.
It's also worth noting that this system does not stop people from joining if authenticate_clients is set to false in the config and the player sends a join request to the server before the server fetches the pb-id, this is intentional as the server has requested …

Added the reject_recently_left_players plugin into the base game

---

.github/workflows/cd.yml
README.md
config/spinoffconfig.py

This PR adds a new workflow file named CD, this workflow gets triggered on pushes and PRs and makes and uploads the following builds as artifacts:
- prefab-linux-x86-64-gui-debug
- prefab-linux-x86-64-server-debug
- prefab-linux-arm64-gui-debug
- prefab-linux-arm64-server-debug
- prefab-mac-x86-64-gui-debug
- prefab-mac-x86-64-server-debug
- prefab-mac-arm64-gui-debug
- prefab-mac-arm64-server-debug
- prefab-windows-x86-gui-debug
- prefab-windows-x86-server-debug
This makes it easier for people to test new commits and review PRs.
[Here it is in action](https://github.com/efroemling/ballistica/actions/runs/7097493079)

Automatic prefab builds for each push and PR

---

src/assets/ba_data/python/bascenev1lib/actor/spaz.py

Power-ups are affecting melee combat, why? Because these can be hit, you take knockback and this puts you at a disadvantage, It's like you punch a wall. 
In the case of hitting your opponent who was nearby, the damage will be less than that received by the great immovable box. Thanks to this pr, it will be less complicated to fight near the power-ups placed in the middle.
Also it doesn't make any sense that you can hit powerups and receive knockback if they disappear with touch, I think this makes it easier for you to grab them if you hit them

 Power-ups affecting melee combat

---

CONTRIBUTORS.md
src/assets/ba_data/python/bauiv1lib/gather/manualtab.py

This is a simple fix that allows player to use ipv6 addresses on the manual tab to connect to servers and maybe their friends party. The method used earlier `socket.gethostbyname` only supports ipv4 so instead i switched it to `socket.getaddrinfo` that support both protocols.
Some video samples here of before and after.
https://github.com/efroemling/ballistica/assets/67740566/ea2ffe79-82b9-4fe1-8d3a-29723a899b37
https://github.com/efroemling/ballistica/assets/67740566/d3b5c066-adf9-45be-ac4f-30ba7e898c1f

Support IPv6 address on manualtab

---

src/assets/ba_data/python/bascenev1lib/actor/flag.py
src/assets/ba_data/python/bascenev1lib/game/football.py

In football, if you grab flag and leave it in a place other than goal area and spawn point of flag, it'll count down from 10 to 1 and then spawn back in it's spawn point, but there is a delay between it disappearing and before it spawns back. Removed that delay so now it should just disappear and spawn back instantaneously.

Spawning time fix

---

config/docker/Dockerfile

Fixes the nightly build failing cause of missing zstd in docker

added zstd to apt install in Dockerfile
