efroemling/ballistica

assets/src/ba_data/python/bastd/tutorial.py

After that in tutorial spaz spawns.

Fixed tutorial (replaced self._map with self.map)

---

assets/src/ba_data/python/bastd/activity/coopscorescreen.py

Game stops after failure in the first round of co-op activity, end screen does not appear.

fix the inactivity of the game after failure

---

assets/src/ba_data/python/bastd/game/football.py

Football description: Score 3.0 (?!) touchdowns.

Fix football description

---

assets/src/ba_data/python/bastd/game/onslaught.py

Game does not start, no waves.

Fix endless onslaught

---

assets/src/ba_data/python/ba/__init__.py
assets/src/ba_data/python/ba/_gameutils.py
assets/src/ba_data/python/bastd/actor/bomb.py
assets/src/ba_data/python/bastd/actor/flag.py
assets/src/ba_data/python/bastd/actor/playerspaz.py
assets/src/ba_data/python/bastd/actor/powerupbox.py
assets/src/ba_data/python/bastd/actor/spazbot.py
assets/src/ba_data/python/bastd/game/assault.py
assets/src/ba_data/python/bastd/game/capturetheflag.py
assets/src/ba_data/python/bastd/game/conquest.py
assets/src/ba_data/python/bastd/game/hockey.py
assets/src/ba_data/python/bastd/game/race.py

ba/_gameutils.py - added function:
```python3
def distance(Tuple[float, float, float], Tuple[float, float, float]) -> float:
```
In some game modes ```player.get_team()``` and ```flag.get_team()``` replaced by ```player.team``` and ```flag.team```
In some actors ```_handle_message_sanity_check``` moved into ```if __debug__:```

Bots AI fixes, and some game modes editings

---

assets/src/ba_data/python/ba/_session.py

Hmm.... In these lines, the variable team_names is set to not None.
```python
if team_names is None:
team_names = ['Good Guys']
if team_colors is None:
team_colors = [(0.6, 0.2, 1.0)]
````
but in following line `self._use_teams` always True
```python
self._use_teams = (team_names is not None)
```

Fix FFA session

---

CONTRIBUTORS.md

Just testing
|   | Type |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

testing PRs

---

CONTRIBUTORS.md

Added myself in contributions file too

---

assets/src/server/ballisticacore_server.py

I realized the script couldn't be executed from other directories so I added the chdir function.
Now the script can be properly executed from anywhere.
If that was intended, feel free to reject the request. Also first pull request :)

Added os.chdir() in ballistica_server.py

---

assets/src/ba_data/python/ba/_freeforallsession.py
assets/src/ba_data/python/ba/_profile.py

Just fixed profile colors in FFA session (characters were white).

Fixed profile colors in ffa session and a bit cleanup

---

CHANGELOG.md
CONTRIBUTORS.md

- Replaced ballistica.net with  [ballistica.net](https://ballistica/net)
- Replaced \_ with \\_; some text was _italic_ because of \_ in object names like \_disconnectClient.

Update CHANGELOG.md for better look in Markdown

---

tools/batools/build.py

Require `rsync` executable in `checkenv` pcommand
|   | Type |
| ✓  | :hammer: Refactoring  |

Add rsync to checkenv

---

assets/src/ba_data/python/ba/_map.py

Currently, if a fixed set of players play for a long time on the same map, they always spawn in the same positions, I don't think it's fun.
|   | Type |
| ✓  | :sparkles: New feature |

Shuffle FFA spawn positions

---

CHANGELOG.md
assets/src/ba_data/python/bastd/ui/gather/manualtab.py

- Replaced some raw-strings with `ba.Lstr`
- Made 'Edit' button instead of just 'Rename'
|   | Type |
| ✓  | :hammer: Refactoring  |
Large UIScale
Medium UIScale
Small UIScale

Clean up Favorites Tab

---

assets/src/ba_data/python/bastd/game/chosenone.py

Fix remaining chosen one bug from #368.
Closes #368.

Finish fixing #368

---

assets/src/ba_data/python/ba/_meta.py
assets/src/ba_data/python/bastd/ui/feedback.py

Updating the link as it was outdated.

Updated Meta Tag System Link

---

CHANGELOG.md
src/ballistica/game/connection/connection_set.cc
src/ballistica/game/connection/connection_set.h
src/ballistica/game/connection/connection_to_client.h
src/ballistica/game/connection/connection_to_client_udp.h
src/ballistica/networking/sockaddr.h

Added a simple check for incoming packets verifying that client address didn't change.

add client address checks 

---

assets/src/ba_data/python/bastd/game/football.py
assets/src/ba_data/python/bastd/game/hockey.py
assets/src/ba_data/python/bastd/game/keepaway.py
assets/src/ba_data/python/bastd/game/kingofthehill.py

Added Epicmode support for keepaway, kingofthehill, football & hockey

Epic mode in keepaway & kingofthehill & football & hockey

---

assets/src/server/ballisticacore_server.py

You forgot to update `VERSION_STR` when you updated the version in the comments
| ✓   | :hammer: Refactoring   |

Refresh VERSION_STR

---

assets/src/ba_data/python/bastd/mainmenu.py
assets/src/ba_data/python/bastd/ui/debug.py

Fixed a bug

---

CONTRIBUTORS.md
assets/src/ba_data/python/bastd/actor/popuptext.py
assets/src/ba_data/python/bastd/ui/serverdialog.py

PB-ID Copy Button

---

assets/src/ba_data/python/bastd/actor/spaz.py

Weak punch sound to reuse (spaz.py)

---

assets/src/ba_data/python/bastd/game/easteregghunt.py

Added epic mode option to Easter egg hunt

Epic mode in Easter egg hunt

---

src/ballistica/scene/node/spaz_node.cc

Remove redundant code

---

assets/src/server/ballisticacore_server.py
src/ballistica/platform/platform.cc

party name as device name for headless 🤔.

changing device name for servers

---

assets/src/ba_data/python/bastd/ui/settings/advanced.py
src/ballistica/app/app_config.cc
src/ballistica/app/app_config.h
src/ballistica/graphics/graphics.cc
src/ballistica/graphics/graphics.h
src/ballistica/logic/connection/connection.cc
src/ballistica/logic/connection/connection.h
src/ballistica/logic/logic.cc

Added ability to check current ping while playing in server.

added ingame ping

---

CONTRIBUTORS.md
assets/src/ba_data/python/bastd/mainmenu.py

funni
| ✓   | :star2: VERY IMPORTANT |

Updated the Copyright Footer :rofl: 

---

assets/src/ba_data/python/bastd/ui/settings/pluginsettings.py

Adding Confirm Window

---

src/assets/ba_data/python/bauiv1lib/settings/plugins.py

This shows the gray color for disabled plugins.

Small Bug in Plugins Window

---

src/assets/ba_data/python/bauiv1lib/profile/edit.py

Fixing a small error

---

src/assets/ba_data/python/bascenev1lib/mainmenu.py

My PR basically just changes the copyright footer to represent the current year (2011-2024), because I think Eric forgets it every year :P 

Update copyright footer

---

src/assets/sphinx/template/conf.py
src/assets/sphinx/template/index.rst
tools/batools/docs.py

Improvements on the sphinx docs generation
Now docs actually show version instead of placeholder
Improvements to home page 
Now generating dummy modules docs aswell
| ✓   | :scroll: Docs          |

Sphinx docs improvement

---

src/assets/ba_data/python/bascenev1lib/actor/spaz.py

It's perfect for anyone who wanted an even tougher bot, powerups that can interfere with health (I already thought of steroids (Now to figure out how the hell do I make a powerup))  or any mods on mechanics they can think of without making this change manually everytime.
This closes #688 
| ✓   | :hammer: Fix what I think was a bug.   |
| ✓   | :scroll: Great for change modders         |

having custom health amount on a spaz

---

config/docker/Dockerfile
config/docker/Dockerfile_arm64

Added pulseaudio-utils to the installed package in docker builds for audio routing and output
Previously gui builds would fail to run because of audio errors unless audio was removed during build process
https://github.com/efroemling/ballistica/wiki/Docker-builds
| ✓   | :hammer: Refactoring   |

added pulseaudio for audio in docker image

---

src/assets/ba_data/python/bascenev1lib/actor/spaz.py

Die Message Fix - Update spaz.py

---

src/assets/ba_data/python/bauiv1lib/chest.py

So Eric, is this good? I have went through the code a bit and thought a lot and this is the best way.
Before:
After:

Removing Timer for Chests for Gold Pass Players

---

CONTRIBUTORS.md

pls add this one (ignore the other one)

CONTRIBUTORS.md (update cuz era told me to + i lowkey wanted to)

---

src/assets/ba_data/python/bauiv1lib/help.py

It's fun.
(Ignore the speed, I used my hands to click)
https://github.com/user-attachments/assets/630b5431-e23e-4ca0-ba0e-783c2afec43f

A Small but Fun Change

---

src/assets/ba_data/python/baclassic/_appsubsystem.py
src/assets/ba_data/python/bascenev1lib/maps.py

*select title* 
*ctrl+c*
*ctrl+v*

Removing the hard-coded lines.

---

src/assets/ba_data/python/bauiv1lib/mainmenu.py

basically changes 2024 to 2025 in the main menu in game, i added myself as a contributor last year and i still didnt get added in the CONTRIBUTORS file.

2025 update main menu

---

src/assets/ba_data/python/bascenev1lib/game/runaround.py
src/assets/ba_data/python/bauiv1lib/colorpicker.py
src/assets/ba_data/python/bauiv1lib/settings/graphics.py

Fixing a few stuff ( moving heart to a bit left in runaround, letting players to edit the hex code for colors, fixing back button for graphics window)

---

.github/workflows/release.yml
README.md

- [removed directory tree from the docker release zip](https://github.com/efroemling/ballistica/commit/71a81647f51672f471e9b8f5c7f9291c11a97253)
- [switched release workflow docker builds to debug](https://github.com/efroemling/ballistica/commit/0635f24cbc2f9788eaee0ca1ae5ae66ab935980f)
- [added nightly build status badge](https://github.com/efroemling/ballistica/commit/70ce24a0db1353d68ef630f762cc125d2cc90c24) to readme
- [removed mac_x86_64 job from release workflow](https://github.com/efroemling/ballistica/pull/811/commits/27c36ffe29fa38a7249bba50664a59a4a5c9ea42) since they are no longer supported
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

switched release workflow docker builds to debug

---

src/assets/ba_data/python/bascenev1/_messages.py
src/assets/ba_data/python/bascenev1lib/actor/spaz.py

Allows customizable time for freezing players instead of just 5 seconds designed only for ice bombs.

Customizable time for Freezing

---

.github/workflows/nightly.yml
.github/workflows/release.yml

| ✓   | :hammer: Refactoring   |

renamed docker image name for release and nightly builds
